package com.ccptl.messmanagment.utils

class Constants {
    companion object{
        const val FIREBASE_LOG_ERROR = "logError"
        const val FIREBASE_ERROR_MSG = "error_msg"
        const val FIREBASE_ERROR_DATE = "error_date"
        const val FIREBASE_ERROR_ACTIVITY = "activity_name"
        const val FIREBASE_ERROR_CODE = "error_code"
        const val FIREBASE_VERSION_NAME = "version_name"

        const val FIREBASE_LOGIN_DATA = "loginData"
        const val FIREBASE_LOGIN_EMAIL = "email"
        const val FIREBASE_LOGIN_PASSWORD = "password"
        const val FIREBASE_LOGIN_DATE = "updated_date"
        const val FIREBASE_USER_TYPE = "user_type"
        const val FIREBASE_USER_ID = "user_id"

        const val FIREBASE_TABLE_DATA = "tableData"
        const val FIREBASE_TABLE_NAME = "table_name"
        const val FIREBASE_TABLE_TOTAL_CHAIR = "table_total_chair"
        const val FIREBASE_TABLE_AVAILABLE_CHAIR = "table_available_chair"
        const val FIREBASE_TABLE_OCCUPY_CHAIR = "table_occupy_chair"
        const val FIREBASE_TABLE_CREATED_AT = "table_created_at"
        const val FIREBASE_TABLE_UPDATED_AT = "table_updated_at"
        const val FIREBASE_TABLE_ID = "table_id"

        const val FIREBASE_CATEGORY_DATA = "categoryData"
        const val FIREBASE_CATEGORY_NAME = "category_name"
        const val FIREBASE_CATEGORY_TYPE = "category_type"
        const val FIREBASE_CATEGORY_ID = "category_id"
        const val FIREBASE_CATEGORY_CREATED_AT = "category_created_at"
        const val FIREBASE_CATEGORY_UPDATED_AT = "category_updated_at"


        const val FIREBASE_MESS_MEMBER_DATA = "messMemberData"
        const val FIREBASE_MESS_MEMBER_ID = "mess_member_id"
        const val FIREBASE_MESS_MEMBER_NAME = "mess_member_name"
        const val FIREBASE_MESS_MEMBER_MOBILE = "mess_member_mobile"
        const val FIREBASE_MESS_TYPE = "mess_type"
        const val FIREBASE_MESS_FROM_DATE = "mess_member_from_date"
        const val FIREBASE_MESS_TO_DATE = "mess_member_to_date"
        const val FIREBASE_MESS_PAYMENT = "mess_member_payment"
        const val FIREBASE_MESS_PAYMENT_MODE = "mess_member_payment_mode"
        const val FIREBASE_MESS_CREATED_AT = "mess_member_created_at"
        const val FIREBASE_MESS_UPDATED_AT = "mess_member_updated_at"
        const val FIREBASE_MESS_CLOSE_AT = "mess_member_close_at"
        const val FIREBASE_MESS_DELETE_AT = "mess_member_delete_at"
        const val FIREBASE_MESS_STATUS = "mess_member_status"

        const val FIREBASE_RESTAURANT_DATA = "restaurantData"
        const val FIREBASE_RESTAURANT_RES_ID = "res_id"
        const val FIREBASE_RESTAURANT_NAME = "res_name"
        const val FIREBASE_RESTAURANT_TYPE = "res_type"
        const val FIREBASE_RESTAURANT_LOCATION = "res_location"
        const val FIREBASE_RESTAURANT_CITY = "res_city"
        const val FIREBASE_RESTAURANT_STATE = "res_state"
        const val FIREBASE_RESTAURANT_TIME = "res_time"
        const val FIREBASE_RESTAURANT_PHONE = "res_phone"
        const val FIREBASE_RESTAURANT_EMAIL = "res_email"
        const val FIREBASE_RESTAURANT_WEBSITE = "res_website"
        const val FIREBASE_RESTAURANT_TOTAL_WORKER = "res_total_worker"
        const val FIREBASE_RESTAURANT_WAITER = "res_waiter"
        const val FIREBASE_RESTAURANT_OUT_SERVICE = "res_out_service"
        const val FIREBASE_RESTAURANT_STATUS = "res_status"
        const val FIREBASE_RESTAURANT_BILL_STATUS = "res_bill_status"
        const val FIREBASE_RESTAURANT_CREATED_AT = "res_created_at"
        const val FIREBASE_RESTAURANT_UPDATED_AT = "res_updated_at"
        const val FIREBASE_RESTAURANT_DELETED_AT = "res_deleted_at"
        const val FIREBASE_RESTAURANT_OWNER_NAME = "res_owner_name"

        const val FIREBASE_CHECK_LAST_ENTRY_DATA = "lastEntryData"
        const val CHECK_LAST_ENTRY_MEMBER_DATA = "checkLastEntryMemberData"
        const val CHECK_LAST_ENTRY_MESS_HISTORY_DATA = "checkLastEntryMessHistoryData"
        const val CHECK_LAST_ENTRY_RESTAURANT_DATA = "checkLastEntryTableData"
        const val RESTAURANT_ID = "restaurant_id"

        const val FIREBASE_MESS_HISTORY_DATA = "messHistoryData"
        const val FIREBASE_MESS_HISTORY_ID = "mess_history_id"
        const val FIREBASE_MESS_HISTORY_MEMBER_ID = "mess_history_member_id"

    }
}